site:
  name: GP-STOR
  site: 'https://djw8605.github.io/gp-stor-website'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Great Plains Scalable Tiered Object Repository
    template: '%s â€” GP-STOR'
  description: "GP-STOR provides distributed, resilient storage infrastructure designed to accelerate research across the Great Plains region."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: GP-STOR
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 800
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
